src/CDE/ContentBundle/Entity/Tag.php
<?php

namespace CDE\ContentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use CDE\ContentBundle\Model\TagInterface;
/**
 * CDE\ContentBundle\Entity\Tag
 *
 * @Gedmo\Tree(type="nested")
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Gedmo\Tree\Entity\Repository\NestedTreeRepository")
 */
class Tag implements TagInterface
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var integer $id
     * 
     * @ORM\ManyToMany(targetEntity="Page", mappedBy="tags")
     */
    private $pages;

    /**
     * @var integer $id
     * 
     * @ORM\ManyToMany(targetEntity="CDE\CartBundle\Entity\Product", mappedBy="tags")
     */
    private $products;

    /**
     * @var string $name
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string $slug
     *
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(name="slug", type="string", length=255, unique=true)
     */
    private $slug;
    
    /**
     * @var boolean $active
     * 
     * @ORM\Column(name="active", type="boolean")
     */
    private $active;

    /**
     * @var integer $lft
     *
     * @Gedmo\TreeLeft
     * @ORM\Column(name="lft", type="integer")
     */
    private $lft;

    /**
     * @var integer $lvl
     *
     * @Gedmo\TreeLevel
     * @ORM\Column(name="lvl", type="integer")
     */
    private $lvl;

    /**
     * @var integer $rgt
     *
     * @Gedmo\TreeRight
     * @ORM\Column(name="rgt", type="integer")
     */
    private $rgt;

    /**
     * @var integer $root
     *
     * @Gedmo\TreeRoot
     * @ORM\Column(name="root", type="integer", nullable=true)
     */
    private $root;
    
    /**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="Tag", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="SET NULL")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="Tag", mappedBy="parent")
     * @ORM\OrderBy({"lft" = "ASC"})
     */
    private $children;
    
    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var datetime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated", type="datetime")
     */
    private $updated;

    public function __toString()
    {
        $parent = $this->getParent();
        if ($parent) {
            return $parent->__toString().' - '.$this->name;
        }
        return $this->name;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Get pages
     * 
     * @return object
     */
    public function getPages()
    {
        return $this->pages;
    }
    
    /**
     * Get products
     * 
     * @return object
     */    
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Tag
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set active
     *
     * @param boolean $active
     * @return Tag
     */
    public function setActive($active)
    {
        $this->active = $active;
        return $this;
    }

    /**
     * Get active
     *
     * @return boolean 
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Set parent
     *
     * @param integer $parent
     * @return Tag
     */
    public function setParent(Tag $parent = null)
    {
        $this->parent = $parent;
        return $this;
    }

    /**
     * Get parent
     *
     * @return string 
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Set created
     *
     * @param datetime $created
     * @return Page
     */
    public function setCreated($created)
    {
        $this->created = $created;
        return $this;
    }

    /**
     * Get created
     *
     * @return datetime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param datetime $updated
     * @return Page
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;
        return $this;
    }

    /**
     * Get updated
     *
     * @return datetime 
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Get lvl
     *
     * @return integer 
     */
    public function getLvl()
    {
        return $this->lvl;
    }

    public function getActiveText()
    {
        if($this->active) {
            return 'Active';
        }
        return 'Disabled';
    }
    
}

src/CDE/ContentBundle/Form/Type/TagType.php
<?php

namespace CDE\ContentBundle\Form\Type;

use Symfony\Component\Form\FormBuilder;
use FOS\UserBundle\Form\Type\ProfileFormType as BaseType;
use Symfony\Component\Form\AbstractType;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('active', 'checkbox', array('required' => FALSE))
            ->add('name')
            ->add('parent', 'entity', array(
                'required' => FALSE,
                'label' => 'Parent Tag',
                'class' => 'CDE\ContentBundle\Entity\Tag',
                'query_builder' => function(EntityRepository $er) {
                    return $er->createQueryBuilder('l')->where('l.lvl = 0');
                },
            ))
            ;
    }
    
    public function getName()
    {
        return 'cde_tag';
    }
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class'=>'CDE\ContentBundle\Entity\Tag',
        ));
    }
}

src/CDE/ContentBundle/Controller/TagController.php
<?php

namespace CDE\ContentBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use CDE\ContentBundle\Form\Type\TagType;
use Symfony\Component\HttpFoundation\Request;


class TagController extends Controller
{
    protected function getTagManager()
    {
        return $this->get('cde_content.manager.tag');
    }
    
    public function indexAction()
    {
        $tags = $this->getTagManager()->getTreeArray();
        return $this->render('CDEContentBundle:Tag:index.html.twig', array(
            'tags' => $tags,
        ));
    }

    public function viewAction($id)
    {
        $tag = $this->getTagManager()->find($id);
        return $this->render('CDEContentBundle:Tag:view.html.twig', array(
            'tag' => $tag,
        ));
    }
    
    public function createAction(Request $request)
    {
        $tag = $this->getTagManager()->create();
        $form = $this->createForm(new TagType(), $tag);
        // Process form
        if ($request->getMethod() === 'POST') {
            $form->bind($request);
            if($form->isValid()) {
                $this->getTagManager()->add($tag);
                return $this->redirect($this->generateUrl('CDEContentBundle_tag_view', array('id' => $tag->getId())));
            }
        }
        // Render form
        return $this->render('CDEContentBundle:Tag:create.html.twig', array(
            'form' => $form->createView()
        ));
    }

    public function updateAction(Request $request, $id)
    {
        $tag = $this->getTagManager()->find($id);
        $form = $this->createForm(new TagType(), $tag);
        // Process form
        if ($request->getMethod() === 'POST') {
            $form->bind($request);
            if($form->isValid()) {
                $this->getTagManager()->add($tag);
                return $this->redirect($this->generateUrl('CDEContentBundle_tag_view', array('id' => $tag->getId())));
            }
        }
        // Render form
        return $this->render('CDEContentBundle:Tag:update.html.twig', array(
            'form' => $form->createView(),
            'tag' => $tag,
        ));
    }
    public function deleteAction(Request $request, $id)
    {
        $tag = $this->getTagManager()->find($id);
        $form = $this->createFormBuilder($tag)->add('id', 'hidden')->getForm();
        // Process form
        if($request->getMethod() === 'POST') {
            if ($this->get('validator')->validate($tag, array('csrf_only'))) {
                $this->get('session')->getFlashBag()->add('notice', "Deleted ".$tag->__toString());
                $this->getTagManager()->remove($tag);
                return $this->redirect($this->generateUrl('CDEContentBundle_tag_index'));
            }
        }
        // Render form
        return $this->render('CDEContentBundle:Tag:delete.html.twig', array(
            'form' => $form->createView(),
            'tag' => $tag,
        ));
    }

}

src/CDE/ContentBundle/Resources/views/Tag/create.html.twig
{% extends '::admin.html.twig' %}

{% block bottomNav %}
    <a href="{{ path('CDEContentBundle_tag_index') }}">
        <li>
            Back to Tags
        </li>
    </a>
{% endblock %}

{% block main %}
    <h1>Create New Tag</h1>
    <form action="{{ path('CDEContentBundle_tag_create') }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}
        <input type="submit" value="Create" />
    </form>
{% endblock %}

src/CDE/ContentBundle/Resources/views/Tag/delete.html.twig
{% extends '::admin.html.twig' %}

{% block bottomNav %}
    <a href="{{ path('CDESubscriptionBundle_update', { 'id': subscription.id }) }}">
        <li>
            Back to Subscription Edit
        </li>
    </a>
    <a href="{{ path('CDESubscriptionBundle_view', { 'id': subscription.id }) }}">
        <li>
            Back to Subscription
        </li>
    </a>
{% endblock %}

{% block main %}
    <h1>Are you sure you want to delete {{ subscription }}?</h1>
    <form action="{{ path('CDESubscriptionBundle_delete', { 'id': subscription.id }) }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}
        <input type="submit" value="Delete" />
    </form>
{% endblock %}

src/CDE/ContentBundle/Resources/views/Tag/index.html.twig
{% extends '::admin.html.twig' %}

{% block bottomNav %}
    <a href="{{ path('CDEContentBundle_index') }}">
        <li>
            Back to Pages
        </li>
    </a>
    <a href="{{ path('CDEContentBundle_tag_create') }}">
        <li>
            New Tag
        </li>
    </a>
{% endblock %}

{% block main %}
    <h1>Tags</h1>
    {% include 'CDEContentBundle:Tag:table.html.twig' %}
{% endblock %}

src/CDE/ContentBundle/Resources/views/Tag/table.html.twig
<table class="data-table" id="tag-table">
    <thead>
        <tr>
            <th class="sortable alpha">parent</th>
            <th class="sortable alpha">name</th>
            <th class="sortable alpha">active</th>
            <th class="desc sortable date">created</th>
            <th class="sortable date">updated</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        {% for parent in tags %}
            <tr>
                <td>
<!--                     No Parent for Parents -->
                </td>
                <td>
                    <a href="{{ path('CDEContentBundle_tag_view', { 'id': parent.id }) }}">{{ parent.name }}</a>
                </td>
                <td>
                    {% if parent.active %}
                        Active
                    {% else %}
                        Disabled
                    {% endif %}
                    
                </td>
                <td>
                    {{ parent.created|date('m/d/y') }}
                </td>
                <td>
                    {{ parent.updated|date('m/d/y') }}
                </td>
                <td>
                    <a href="{{ path('CDEContentBundle_tag_delete', { 'id': parent.id }) }}">delete</a>
                </td>
                <td>
                    <a href="{{ path('CDEContentBundle_tag_update', { 'id': parent.id }) }}">edit</a>
                </td>
            </tr>
            {% for child in parent.__children %}
                <tr>
                    <td>
                        {{ parent.name }}
                    </td>
                    <td>
                        <a href="{{ path('CDEContentBundle_tag_view', { 'id': child.id }) }}">{{ child.name }}</a>
                    </td>
                    <td>
                        {% if child.active %}
                            Active
                        {% else %}
                            Disabled
                        {% endif %}
                    </td>
                    <td>
                        {{ child.created|date('m/d/y') }}
                    </td>
                    <td>
                        {{ child.updated|date('m/d/y') }}
                    </td>
                    <td>
                        <a href="{{ path('CDEContentBundle_tag_delete', { 'id': child.id }) }}">delete</a>
                    </td>
                    <td>
                        <a href="{{ path('CDEContentBundle_tag_update', { 'id': child.id }) }}">edit</a>
                    </td>
            </tr>            
            {% endfor %}
        {% endfor %}
    </tbody>
</table>

src/CDE/ContentBundle/Resources/views/Tag/update.html.twig
{% extends '::admin.html.twig' %}

{% block bottomNav %}
    <a href="{{ path('CDEContentBundle_tag_index') }}">
        <li class="meta">
            Back to Tags
        </li>
    </a>
{% endblock %}

{% block main %}
    <h1>Update Tag</h1>
    <h2><a href="{{ path('CDEContentBundle_tag_view', { 'id': tag.id }) }}">{{ tag }}</a></h2>
    <form action="{{ path('CDEContentBundle_tag_update', { 'id': tag.id }) }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}
     <input type="submit" value="Update" />
     </form>
{% endblock %}

src/CDE/ContentBundle/Resources/views/Tag/view.html.twig
{% extends '::admin.html.twig' %}

{% block bottomNav %}
    <a href="{{ path('CDEContentBundle_tag_index') }}">
        <li>
            Back to Tags
        </li>
    </a>
    <a href="{{ path('CDEContentBundle_tag_update', { 'id': tag.id}) }}">
        <li>
            Edit Tag
        </li>
    </a>
    <a href="{{ path('CDEContentBundle_tag_create') }}">
        <li>
            New Tag
        </li>
    </a>
{% endblock %}

{% block main %}
    <h1>{{ tag }}</h1>
    <ul class="data-list">
        <li>
            <div class="key">Parent</div><div class="value">{{ tag.parent }}</div>
        </li>
        <li>
            <div class="key">Name</div><div class="value">{{ tag.name }}</div>
        </li>
        <li>
            <div class="key">Status</div><div class="value">{{ tag.activeText }}</div>
        </li>
    </ul>
{% endblock %}